# -*- coding: utf-8 -*-
"""preProcessing_nn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XaUviIUFE4X6QwJYfJsQvaDLje_mdaJ0
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

def preprocess(df):
            

    #replace turns with number, https://pbpython.com/categorical-encoding.html
    turn_nums = {'Slight-Left-Turn': -1.0, 'Move-Forward': 0.0, 'Slight-Right-Turn': 1.0, 'Sharp-Right-Turn': 2.0}
    df.replace(turn_nums)       
    # Columns desciption:
    # Sensor data
        
    #Separate the data into x and y variables
    x = df.iloc[:,0:23]
    y = df.iloc[:,24]

    print(x)
        
    #https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
    from sklearn.model_selection import train_test_split
    xTrain, xTest, yTrain, yTest = train_test_split(x, y, train_size = 0.80)
        
    # Compute sde, mean of the data  
    scaler = StandardScaler()
    scaler.fit(x)
        
    # Transform the x data
    x = scaler.transform(x)

              
    # Convert y data to lists

    y = y.tolist()
        
    # Concatenate a column of '1's to the x data as bias  
    x = np.c_[x, np.ones((len(x), 1))]
              
    return df

